// AUTO-GENERATED - do not edit.
declare const DOTA_UNIT_TARGET_FLAGS: {
	DOTA_UNIT_TARGET_FLAG_NONE: bigint
	DOTA_UNIT_TARGET_FLAG_RANGED_ONLY: bigint
	DOTA_UNIT_TARGET_FLAG_MELEE_ONLY: bigint
	DOTA_UNIT_TARGET_FLAG_DEAD: bigint
	DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES: bigint
	DOTA_UNIT_TARGET_FLAG_NOT_MAGIC_IMMUNE_ALLIES: bigint
	DOTA_UNIT_TARGET_FLAG_INVULNERABLE: bigint
	DOTA_UNIT_TARGET_FLAG_FOW_VISIBLE: bigint
	DOTA_UNIT_TARGET_FLAG_NO_INVIS: bigint
	DOTA_UNIT_TARGET_FLAG_CAN_BE_SEEN: bigint
	DOTA_UNIT_TARGET_FLAG_NOT_ANCIENTS: bigint
	DOTA_UNIT_TARGET_FLAG_PLAYER_CONTROLLED: bigint
	DOTA_UNIT_TARGET_FLAG_NOT_DOMINATED: bigint
	DOTA_UNIT_TARGET_FLAG_NOT_SUMMONED: bigint
	DOTA_UNIT_TARGET_FLAG_NOT_ILLUSIONS: bigint
	DOTA_UNIT_TARGET_FLAG_NOT_ATTACK_IMMUNE: bigint
	DOTA_UNIT_TARGET_FLAG_MANA_ONLY: bigint
	DOTA_UNIT_TARGET_FLAG_CHECK_DISABLE_HELP: bigint
	DOTA_UNIT_TARGET_FLAG_NOT_CREEP_HERO: bigint
	DOTA_UNIT_TARGET_FLAG_OUT_OF_WORLD: bigint
	DOTA_UNIT_TARGET_FLAG_NOT_NIGHTMARED: bigint
	DOTA_UNIT_TARGET_FLAG_PREFER_ENEMIES: bigint
	DOTA_UNIT_TARGET_FLAG_RESPECT_OBSTRUCTIONS: bigint
}
type DOTA_UNIT_TARGET_FLAGS = bigint
