// AUTO-GENERATED - do not edit.
declare const DOTA_UNIT_TARGET_TYPE: {
	DOTA_UNIT_TARGET_NONE: bigint
	DOTA_UNIT_TARGET_HERO: bigint
	DOTA_UNIT_TARGET_CREEP: bigint
	DOTA_UNIT_TARGET_BUILDING: bigint
	DOTA_UNIT_TARGET_COURIER: bigint
	DOTA_UNIT_TARGET_HEROES_AND_CREEPS: bigint
	DOTA_UNIT_TARGET_OTHER: bigint
	DOTA_UNIT_TARGET_ALL: bigint
	DOTA_UNIT_TARGET_TREE: bigint
	DOTA_UNIT_TARGET_CUSTOM: bigint
	DOTA_UNIT_TARGET_SELF: bigint
	DOTA_UNIT_TARGET_BASIC: bigint
}
type DOTA_UNIT_TARGET_TYPE = bigint
