// AUTO-GENERATED - do not edit.
declare enum DOTAHullSize {
	DOTA_HULL_SIZE_NONE = 0,
	DOTA_HULL_SIZE_SMALLEST = 1,
	DOTA_HULL_SIZE_SMALL = 2,
	DOTA_HULL_SIZE_REGULAR = 3,
	DOTA_HULL_SIZE_HERO = 4,
	DOTA_HULL_SIZE_BIG_HERO = 5,
	DOTA_HULL_SIZE_SIEGE = 6,
	DOTA_HULL_SIZE_TOWER = 7,
	DOTA_HULL_SIZE_LARGE = 8,
	DOTA_HULL_SIZE_HUGE = 9,
	DOTA_HULL_SIZE_BUILDING = 10,
	DOTA_HULL_SIZE_BARRACKS = 11,
	DOTA_HULL_SIZE_FILLER = 12
}
