// AUTO-GENERATED - do not edit.
declare const DOTA_UNIT_TARGET_TEAM: {
	DOTA_UNIT_TARGET_TEAM_NONE: bigint
	DOTA_UNIT_TARGET_TEAM_FRIENDLY: bigint
	DOTA_UNIT_TARGET_TEAM_ENEMY: bigint
	DOTA_UNIT_TARGET_TEAM_BOTH: bigint
	DOTA_UNIT_TARGET_TEAM_CUSTOM: bigint
}
type DOTA_UNIT_TARGET_TEAM = bigint
