// AUTO-GENERATED - do not edit.
declare const enum DOTAGameUIState {
	DOTA_GAME_UI_STATE_INVALID = 0,
	DOTA_GAME_UI_STATE_LOADING_SCREEN = 1,
	DOTA_GAME_UI_DOTA_INGAME = 2,
	DOTA_GAME_UI_STATE_DASHBOARD = 3
}
