// AUTO-GENERATED - do not edit.
declare namespace MenuSDK {
	const Tokens: TokenSet<{
		Accent: string
		AccentMuted: string
		AccentSurface: string
		PopoverBg: string
		AccentA6: string
		AccentA15: string
		AccentA25: string
		AccentA30: string
		AccentA40: string
		WindowBg: string
		PanelBorder: string
		CardBg: string
		CardBorder: string
		PillBg: string
		PillBorder: string
		SurfaceBg: string
		SurfaceBorder: string
		InputBg: string
		InputBorder: string
		InputBorderHover: string
		ButtonBorder: string
		TextPrimary: string
		TextBody: string
		TextBright: string
		TextDim: string
		TextSection: string
		TextCardTitle: string
		TextNavIdle: string
		TextNavHover: string
		TextMuted: string
		TextControl: string
		TextDisabled: string
		TextTooltip: string
		SwitchOff: string
		Knob: string
		SliderTrack: string
		FilterDivider: string
		ScrollThumb: string
		ScrollThumbHover: string
		RowHover: string
		NavRowHover: string
		MenuItemBg: string
		MenuItemText: string
		GlassBg: string
		GlassBgMenu: string
		GlassBgPanel: string
		TriggerHover: string
		GlassBorder: string
		GlassHighlight: string
		PillInset: string
		GlassBlur: string
		BackdropDim: string
		BackdropDimSoft: string
		LockedZone: string
		LockedMark: string
		MarkNew: string
		MarkChanged: string
		Danger: string
		DangerSoft: string
		DangerBg: string
		DangerBorder: string
		StatusGood: string
		StatusWarn: string
		StatusBad: string
	}>
}
