// AUTO-GENERATED - do not edit.
declare class DataTeamPlayer {
	public readonly properties: EntityPropertiesNode
	public get AutoCourierAutoBurst(): boolean
	public get AutoCourierAutoDeliver(): boolean
	public get DeliverWhileVisibleOnly(): boolean
	public get TotalEarnedGold(): number
	public get ReliableGold(): number
	public get UnreliableGold(): number
	public get StartingPosition(): number
	public get TotalEarnedXP(): number
	public get SharedGold(): number
	public get HeroKillGold(): number
	public get CreepKillGold(): number
	public get BuildingGold(): number
	public get OtherGold(): number
	public get ComebackGold(): number
	public get CreepDenyGold(): number
	public get TPScrollsPurchased(): number
	public get IncomeGold(): number
	public get NetWorth(): number
	public get DenyCount(): number
	public get LastHitCount(): number
	public get LastHitStreak(): number
	public get LastHitMultikill(): number
	public get NearbyCreepDeathCount(): number
	public get ClaimedDenyCount(): number
	public get ClaimedMissCount(): number
	public get MissCount(): number
	public get PossibleHeroSelection(): number
	public get BuybackCooldownTime(): number
	public get BuybackGoldLimitTime(): number
	public get BuybackCostTime(): number
	public get CustomBuybackCooldown(): number
	public get Stuns(): number
	public get Healing(): number
	public get TowerKills(): number
	public get RoshanKills(): number
	public get ObserverWardsPlaced(): number
	public get SentryWardsPlaced(): number
	public get CreepsStacked(): number
	public get CampsStacked(): number
	public get RunePickups(): number
	public get GoldSpentOnSupport(): number
	public get HeroDamage(): number
	public get WardsPurchased(): number
	public get WardsDestroyed(): number
	public get Items(): number[]
	public get Parity(): number
	public get InventoryParent(): number
	public get StashEnabled(): boolean
	public get TransientCastItem(): number
	public get KillsPerOpposingTeamMember(): number[]
	public get SuggestedAbilities(): number[]
	public get SuggestedAbilityWeights(): number[]
	public get SuggestedPregameItems(): number[]
	public get SuggestedItemSequences(): number[]
	public get SuggestedHeroes(): number[]
	public get SuggestedHeroesWeights(): number[]
	public get DamageByTypeReceivedPreReduction(): number[]
	public get DamageByTypeReceivedPostReduction(): number[]
	public get CommandsIssued(): number
	public get GoldSpentOnConsumables(): number
	public get GoldSpentOnItems(): number
	public get GoldSpentOnBuybacks(): number
	public get GoldLostToDeath(): number
	public get IsNewPlayer(): boolean
	public get IsGuidePlayer(): boolean
	public get PlayerSteamID(): bigint
	public get SmokesUsed(): number
	public get NeutralTokensFound(): number
	public get WatchersTaken(): number
	public get LotusesTaken(): number
	public get TormentorKills(): number
	public get CourierKills(): number
	public get PossibleHeroFacetSelection(): bigint
	public get ItemSlots(): QuickBuySlot[]
}
